Update gensim/models/rpmodel.py
"scipy.linalg.blas.fblas" has been replaced by "scipy.linalg.blas"

Fixes the following error when running the rpmodel.py:
ERROR: AttributeError: 'module' object has no attribute 'fblas'

Others have experience this error: https://github.com/Theano/Theano/issues/1144

Changing as shown in the above in the .py and recompiling the .pyc worked for me!

Thanks for a great package!

Andrew