Fix docstring for WikiCorpus
After 16h trying to run the commands in the docstring, I got a message saying that 

    AttributeError: 'WikiCorpus' object has no attribute 'saveAsText'

The method does not exist anymore.